/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef VISION_NATIVE_CARBONVISION_H
#define VISION_NATIVE_CARBONVISION_H

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_carbondata_vision_model_ModelManager */

#ifndef _Included_org_apache_carbondata_vision
#define _Included_org_apache_carbondata_vision
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_carbondata_vision_model_ModelManager
 * Method:    loadKNNSearchModel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_carbondata_vision_model_ModelManager_loadKNNSearchModel
    (JNIEnv *, jclass, jstring);


/*
 * Class:     org_apache_carbondata_vision_algorithm_impl_KNNSearch
 * Method:    calcDistanceSet
 * Signature: ([B[B[FLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_carbondata_vision_algorithm_impl_KNNSearch_calcDistanceSet
    (JNIEnv *, jobject, jbyteArray, jbyteArray, jfloatArray, jstring);

/*
 * Class:     org_apache_carbondata_vision_algorithm_impl_KNNSearch
 * Method:    calcDistanceSetNative
 * Signature: (JJ[FLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_carbondata_vision_algorithm_impl_KNNSearch_calcDistanceSetNative
    (JNIEnv *, jobject, jlong, jlong, jfloatArray, jstring);

#ifdef __cplusplus
}
#endif
#endif

#endif //VISION_NATIVE_CARBONVISION_H
